# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install dependencies and MCP packages
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install mcp fastmcp

# Copy application code
COPY . .

# Create Desktop directory for PRESENTATIONS_DIR
RUN mkdir -p /root/Desktop /root/Desktop/MyPPT

#Expose nothing (stdio server)

# Start the MCP server
CMD ["python", "enhanced_ppt_server.py"]
